# This is both an example `.artisan.yml` file
# and the actual configuration for building the
# Artisan CI project against itself. :)

# When running locally, everything that can be built
# given the labels will be built. Other jobs will be
# skipped. If the jobs are run globally then jobs that
# can be run locally will be run locally and non-local
# jobs will be sent to the global farm.

# Give a list of farms that this project can execute on.
farms:
  # Which web servers should we send requests to.
  # The default is `https://farms.artisan.io` if not given.
  sources:
    - 'https://farms.artisan.io'

  # Allow the project to run on Community farms.
  community: true

  # Except don't run on the following farms. Sorry @artisan-bot!
  omit:
    - 'gh/artisan-bot'

jobs:
  # Documentation Builds
  - name: 'docs'
    script: '.artisan/docs.py'
    duration: 5 # This job should take 5 minutes or less.
    labels:
      python: '>=2.7'

      # Python package versions
      python-virtualenv: '>=15.1.0'
      python-setuptools: '>=0.9.8'

      # Make sure that documentation
      # can build on all platforms.
      matrix:
        platform:
          - 'linux'
          - 'osx'
          - 'windows'

  # Flake8 Style Checking
  - name: 'flake8'
    script: '.artisan/flake8.py'
    duration: 5
    labels:
      python: '>=2.7'

      # Python package versions
      python-virtualenv: '>=15.1.0'
      python-setuptools: '>=0.9.8'

  # Test Builds on Many Platforms
  - name: 'tests'
    script: '.artisan/tests.py'
    duration: 5
    labels:

      # Python package versions
      python-virtualenv: '>=15.1.0'
      python-setuptools: '>=0.9.8'

      # Matrixes allow easy expansion of repeated values.
      # NOTE: You must use `include` in order to have multiple
      # matrix entries.
      include:

        # Matrix for CPython builds.
        - matrix:
            platform:
              - 'ubuntu>=12.04'  # Ubuntu
              - 'osx>=10'        # Mac OSX
              - 'windows>=8'     # Windows
              - 'centos|rhel'    # CentOS or RedHat
              - 'solaris'        # Solaris
            python:
              - '==2.7'   # CPython 2.7
              - '==3.3'   # CPython 3.3
              - '==3.4'   # CPython 3.4
              - '==3.5'   # CPython 3.5
              - '==3.6'   # CPython 3.6
            # `include` within a `matrix` add entries.
            include:
              - python: '==3.7'
                platform: 'ubuntu>=12.04'

            # `omit` within a matrix remove entries.
            omit:
              - python: '==3.3'
                platform: 'solaris'
              - python: '==3.4'
                platform: 'solaris'
              - python: '==3.3'
                platform: 'centos|rhel'
              - python: '==3.4'
                platform: 'centos|rhel'

        # Matrix for PyPy builds.
        - matrix:
            platform:
              - 'ubuntu>=12.04'
            python:
              - 'pypy2>=5.6.0'   # PyPy2 (~2.7)
              - 'pypy3>=5.5'     # PyPy3 (~3.3)

        # Matrix for builds with VirtualBox
  - name: 'tests-virtualbox'
    script: '.artisan/tests.py'
    duration: 20
    labels:
      matrix:
        platform:
          - 'ubuntu>=14.04'
          - 'windows>=10'
        python:
          - '==2.7'
          - '==3.5'
          - '==3.6'
        virtualbox: '>=5.1.14'

# Allow the PyPy builds to fail without failing the whole build.
allow_failure:
  - python: 'pypy2>=5.6.0'
  - python: 'pypy3>=5.5'
