language: python
sudo: false

matrix:
  include:
    # Flake8 Style Checking
    - python: 3.5
      env: TOXENV=flake8

    # Flake8 Linter
    - python: 3.5
      env: TOXENV=docs

    # Linux CPython Builds (w/ VirtualBox)
    - python: 2.7
      sudo: required
      dist: trusty
      env:
        - TOXENV=py27
        - VIRTUALBOX=true

    - python: 3.3
      sudo: required
      dist: trusty
      env:
        - TOXENV=py33
        - VIRTUALBOX=true

    - python: 3.4
      sudo: required
      dist: trusty
      env:
        - TOXENV=py34
        - VIRTUALBOX=true

    - python: 3.5
      sudo: required
      dist: trusty
      env:
        - TOXENV=py35
        - VIRTUALBOX=true

    - python: 3.6-dev
      sudo: required
      dist: trusty
      env:
        - TOXENV=py36
        - VIRTUALBOX=true

    - python: nightly
      sudo: required
      dist: trusty
      env:
        - TOXENV=py37
        - VIRTUALBOX=true

    # Linux PyPy Build
    - python: pypy-5.4
      env: TOXENV=pypy

    # OSX CPython Builds
    - language: generic
      os: osx
      env: TOXENV=py27
    - language: generic
      os: osx
      env: TOXENV=py35
    - language: generic
      os: osx
      env: TOXENV=py36

cache:
  - pip
  - directories:
    - ${HOME}/.cache

install:
  - chmod a+x ./.travis/install.sh ./.travis/run.sh ./.travis/upload_coverage.sh
  - ./.travis/install.sh

script:
  - ./.travis/run.sh

after_success:
  - ./.travis/upload_coverage.sh

notifications:
  email: false

branches:
  only:
  - master
  - release
